### ISSUE TITLE
Button not visible in "dark mode"

### ISSUE THREAD

**Issue by Timbobeek** [vkmicro/GB_IssueTracking#11]
**Describe the suggestion / bug**
The three dots button in the main menu is impossible to see in "dark mode"

**Explanation**
Dark mode is gray and black - needs to be more contrasting in order to be visible.

**Screenshots**

<img src="https://user-images.githubusercontent.com/68671029/124524414-9947a200-ddc0-11eb-8ed5-34bb27c3299f.png" width="250" height="380">

**Device information**
 - Device: Samsung Galaxy S6 Edge
 - OS: Android 7.0

**Comment by vkmicro** [comment]
I got similar feedback from another person, this is def 1 of the main things to change, kind of overlooked it.

**Comment by vkmicro** [comment]
![2](https://user-images.githubusercontent.com/17531168/128589245-4a65149c-1f4c-425d-90b3-c02a30e3a6d5.PNG)
![1](https://user-images.githubusercontent.com/17531168/128589246-41dc95f1-5c54-4cdf-8947-12270ff84017.PNG)
