### ISSUE TITLE
Unable to enter symbols into "Notes" window

### ISSUE THREAD

**Issue by Timbobeek** [vkmicro/GB_IssueTracking#2]
**Describe the suggestion / bug**
Unable to enter any symbols/characters into "Notes" window

**Steps to reproduce the behavior**
1. Tap on "New Routine"
2. Tap on "Add Exercise"
3. Tap on "Add Exercise"
4. Tap on "Notes"
5. Tap on the pop-up window

**Actual Result**
Nothing happens once the "Notes" window opens, tapping on it does not trigger a cursor, making it impossible to enter any symbols into the window

**Expected Result**
A cursor appears in the window as soon as the "Notes" window opens

**Screenshots**

https://user-images.githubusercontent.com/68671029/124509190-1e1dc600-dd97-11eb-87c9-ba055997eef2.mp4

**Device information**
 - Device: Samsung Galaxy S6 Edge
 - OS: Android 7.0

**Additional context**
I think this has worked on a previous version, this might be a regression bug.

**Comment by vkmicro** [comment]
to edit notes you have to go into 'edit exercise' mode.
Let me know if you think this should be changed.

**Comment by Timbobeek** [comment]
Makes sense. Perhaps, I would change the visual of the "Notes" and "Rest between sets" in a non-editable mode, so that they don't look like the rest of the buttons. Maybe, do not frame them in blue at all  in a "view" mode, so these two look like the other parts of the exercise (exercise, sets completion, repetitions, etc..), and have the information visible right away, so you don't have to click on anything to see "notes" and "rest between sets". Obviously, there could be other, better solutions!

**Comment by vkmicro** [comment]
I changed it so that if there are no notes, the button just simply gets disabled for that exercise as to avoid confusion and not have it popup and be empty.

![2](https://user-images.githubusercontent.com/17531168/128606331-9caf754b-2204-4ee8-a2fb-d9a2e0adbc9e.PNG)
![1](https://user-images.githubusercontent.com/17531168/128606332-ffc06239-e3c0-4989-9db5-cd2e9df4fe41.PNG)
