### ISSUE TITLE
Dysfunctional "Rest between sets" button 

### ISSUE THREAD

**Issue by Timbobeek** [vkmicro/GB_IssueTracking#4]
**Describe the suggestion / bug**
Dysfunctional "Rest between sets" button 

**Steps to reproduce the behavior**
1. Tap on "New routine"
2. Tap on "Add Exercise"
3. Tap on "Add Exercise"
4. Tap on "Rest Between Sets"

**Actual Result**
Button changes color, but nothing happens after

**Expected Result**
A new pop-up window opens with a timer

**Screenshots**

https://user-images.githubusercontent.com/68671029/124511911-cc783a00-dd9c-11eb-8367-51aa410f52f7.mp4

**Device information**
 - Device: Samsung Galaxy S6 Edge
 - OS: Android 7.0

**Additional context**
N/A

**Comment by vkmicro** [comment]
Rest between sets button only functions if you input 'rest time' when creating a new exercise.
I guess I could make it 'grey out' when there's no rest time input into the exercise.

**Comment by Timbobeek** [comment]
Yes, same thing I have mentioned in a previous report about "notes" button.

**Comment by vkmicro** [comment]
![RestBetweenSets](https://user-images.githubusercontent.com/17531168/142375397-9ce7c19c-90b3-49bb-bcf4-5eb4daeea494.PNG)

fixed
