### ISSUE TITLE
Tiny menu/buttons (accessibility concern)

### ISSUE THREAD

**Issue by Timbobeek** [vkmicro/GB_IssueTracking#5]
**Describe the suggestion / bug**
The buttons in the app are tiny, hard to tap even with small fingers, and could be hard to see to a user

**Screenshots**
<img src="https://user-images.githubusercontent.com/68671029/124512956-46112780-dd9f-11eb-9751-d112f389261d.png" width="250" height="380">

**Device information**
 - Device: Samsung Galaxy S6 Edge
 - OS: Android 7.0

**Additional context**
N/A

**Comment by vkmicro** [comment]
Solution to this would be similar to the suggested fix in this issue [https://github.com/vkmicro/GB_IssueTracking/issues/7](https://github.com/vkmicro/GB_IssueTracking/issues/7 )

**Comment by vkmicro** [comment]
Potentially fixed this issue in the most recent version. Needs testing
