### ISSUE TITLE
Languages besides English not supported

### ISSUE THREAD

**Issue by Timbobeek** [vkmicro/GB_IssueTracking#6]
**Describe the suggestion / bug**
English is the only language supported in the app 

**If Suggestion, write explanation**
I would suggest either having the app translated into various languages later or having the app support non-English keyboards

**Device information**
 - Device: Samsung Galaxy S6 Edge
 - OS: Android 7.0

**Comment by vkmicro** [comment]
Oh i never noticed it's unable to take input from non english typing. I'll have to look into it, I think i should be able to make that function easily.
Unsure about translating the entire interface to other languages, I'll look into adding translator to the app though.

**Comment by vkmicro** [comment]
Should be addressed with new fonts i've added.
Also added feature to select from multiple available fonts

**Comment by vkmicro** [comment]
# #16
