### ISSUE TITLE
"Long Rest" timer off by a second

### ISSUE THREAD

**Issue by Timbobeek** [vkmicro/GB_IssueTracking#8]
**Describe the suggestion / bug**
"Long Rest" timer off by a second. For example, when you set the timer for 6 seconds, it starts the countdown from 5 seconds.

**Steps to reproduce the behavior**
1. Tap on "New Routine"
2. Tap on "Long Rest"
3. Tap on "Edit Long Rest Time"
4. Enter any time
5. Tap "Set"

**Screenshots**

https://user-images.githubusercontent.com/68671029/124516265-dd2dad80-dda6-11eb-80fb-1b50ebee669d.mp4

**Device information**
 - Device: Samsung Galaxy S6 Edge
 - OS: Android 7.0

**Comment by vkmicro** [comment]
has been resolved in the latest version 👍
