### ISSUE TITLE
Cursor is not triggered in "Other notes"

### ISSUE THREAD

**Issue by Timbobeek** [vkmicro/GB_IssueTracking#9]
**Describe the suggestion / bug**
When tapping on "Other notes" when adding an exercise, a window for notes opens. Intuitively, one would start typing and entering notes. However, nothing happens, because the cursor does not appear in the window until you tap on the window. I would make it so that as soon as you select "Other notes", it triggers a cursor, so that a user can start typing right away.  

**If Bug report**
1. Tap on "New Routine"
2. Tap on "Add Exercise"
3. Tap on "Other notes" option
4. Type in any characters

**Screenshots**

https://user-images.githubusercontent.com/68671029/124516930-6abdcd00-dda8-11eb-836c-fdeede911067.mp4

**Device information**
 - Device: Samsung Galaxy S6 Edge
 - OS: Android 7.0

**Comment by vkmicro** [comment]
Oh, interesting. Should be able to fix this 1 fairly easily

**Comment by vkmicro** [comment]
This issue has been addressed and will no longer be a problem in the future versions
